### ISSUE TITLE
您好。在词汇量上可有好的建议？chinglish已让心底在害怕语法。

### ISSUE THREAD

**Issue by BeatsKitano** [linesh-simplicity/ielts#1]

**Comment by EthanLin-TWer** [comment]
您好，您的困惑是词汇还是语法？词汇的话，我使用的有几个途径：

* 关注微信小程序“趣单词打卡” - 选择词包“雅思核心词-精编版”开启打卡练习，共3500词左右
* 使用听力常见词汇表熟悉：http://ielts.xdf.cn/202104/11168450.html
* 使用本仓库云盘分享中的“阅读-同义替换词”进行熟悉

词汇的话个人建议就是两个：一个是贵在坚持、日子有功；一个是建议在背诵的同时同步进行听力、阅读、写作等练习，能更快熟悉单词在场景中的应用。

**Comment by BeatsKitano** [comment]
**感谢您的回复。**
* 您写到第一次考就是6.5分，想来英文基础还好。而对于我，英文是比较苦恼的事，词汇倒也不怕，花功夫记。而语法方面确实感到为难。比如各种时态，比写下无数个if else或switch case要难很多。
* 但我希望能够掌握好英文，无意间在此找到您的资料。“取法于上,仅得为中”，虽然只有大学英文四级的水平，干脆就往雅思上努力，看能不能有一个好的效果。
**再次感谢您的回复以及建议。**
**祝好！**

**Comment by EthanLin-TWer** [comment]
学习一项新的技能本来也是一件不舒适的事，会有很多挑战，个人感受真的就是**要有信心，持之以恒**（健身3个月然后放弃治疗又准备再来的我悟出来的…），等待量变达到质变的过程。这是我司前同事备考雅思的经历，里面提到的听抄我觉得也是有效的办法：https://kb.cnblogs.com/page/152269/ 。坚持下去，保持信心。共勉~
