### ISSUE TITLE
笔记无法打开

### ISSUE THREAD

**Issue by GXL911** [linesh-simplicity/ielts#2]
文章最后的笔记链接无法打开，显示没有授权，可以调整一下嘛？感谢

**Comment by EthanLin-TWer** [comment]
感谢反馈！是因为我附的不是个公开链接，可以试试这个吗？我会同步更新下`README`。
https://ethan-lin.gitbook.io/ielts/

**Comment by GXL911** [comment]
这个好像是可以的，十分感谢你的经验分享！
